### PR TITLE
Use </br> instead of \

### PR DESCRIPTION
**Pull request by yahiheb**
[Here](https://walletsrecovery.org/recovery-docs/casahodl-recovery.html) I think `\` screwed it up .
Maybe `</br>` will fix that.

line ending

### CODE REVIEW

**Comment by nvk** [comment]
Use double returns and MD interpreter will see it.

Ie:

Line one

Line two 

Line three

**Comment by yahiheb** [comment]
But don't you think that will result in a lot of vertical space?

**Comment by nvk** [comment]
It will add a line in between in some parsers, in others it will just return to the next line. Markdown is a mess. Don’t sweat it. It can have extra like between thaem if that’s what looks best.

**Comment by yahiheb** [comment]
I will go with the double returns.
One other thing should we change the file name to casakeymaster-recovery?

**Pull request merged**
