### PR TITLE
Nitpicking

### PR DESCRIPTION
**Pull request by yahiheb**

### CODE REVIEW

**Comment by nvk** [comment]
Some conflicts there.

**Comment by yahiheb** [comment]
Should we use the word `Archive` or `Archived`?

**Comment by nvk** [comment]
`Archive` sounds better in this case.

**Comment by yahiheb** [comment]
You mean it should be across the entire file right?

**Comment by nvk** [comment]
Yes, should be this doc's style.

**Comment by nvk** [comment]
Since you are there want to change "Docs Unofficial" to [Unofficial Docs]

**Pull request merged**
